version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
      - "3000:3000"
    volumes:
      - ./src/app:/usr/share/nginx/html
      - ./src/server:/app/src/server
      - sqlite_data:/app/src/data
    environment:
      - NODE_ENV=development

volumes:
  sqlite_data:
